services:
  mariadb:
    image: mariadb:lts
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: anprdata
      MARIADB_USER: user
      MARIADB_PASSWORD: userpassword
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - pol-assessment-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8088:80"
    depends_on:
      - mariadb
    networks:
      - pol-assessment-network

networks:
  pol-assessment-network:
    external: true

volumes:
  mariadb_data: