services:
  mariadb:
    image: mariadb:lts
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: anprdata
      MARIADB_USER: user
      MARIADB_PASSWORD: userpassword
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./Database/db-docker/init-sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - pol-assessment-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8088:80"
    depends_on:
      - mariadb
    networks:
      - pol-assessment-network

  anpr-dataprocessor-webapi:
    image: anpr-dataprocessor-webapi-image
    container_name: anpr-dataprocessor-webapi-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Swagger__Enabled=true
      - Database__ConnectionString=Server=mariadb-container;Database=anprdata;User=user;Password=userpassword;
    ports:
      - "5100:8080"
      - "5101:8081"
    depends_on:
      - mariadb
    networks:
      - pol-assessment-network

  anpr-enricher-app:
    image: anpr-enricher-app-image
    container_name: anpr-enricher-app-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AnprDataProcessor__BaseUrl=http://anpr-dataprocessor-webapi-container:8080/api/
    depends_on:
      - anpr-dataprocessor-webapi
    networks:
      - pol-assessment-network
    volumes:
      - ./HotFolders:/app/HotFolders

  anpr-frontend-webapi:
    image: anpr-frontend-webapi-image
    container_name: anpr-frontend-webapi-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Swagger__Enabled=true
      - Database__Anpr__ConnectionString=Server=mariadb-container;Database=anprdata;User=user;Password=userpassword;
      - Database__WebApi__ConnectionString=Server=mariadb-container;Database=webapi;User=user;Password=userpassword;
    ports:
      - "5200:8080"
      - "5201:8081"
    networks:
      - pol-assessment-network

  anpr-frontend:
    image: anpr-frontend-image
    container_name: anpr-frontend-container
    environment:
      - API_URL=http://anpr-frontend-webapi-container:8080/api/
    ports:
      - "5300:80"
    networks:
      - pol-assessment-network

networks:
  pol-assessment-network:
    external: true

volumes:
  mariadb_data:

# docker network create pol-assessment-network
# docker-compose up -d
