services:
  anpr-enricher:
    image: anpr-enricher-image
    container_name: anpr-enricher-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AnprDataProcessor__BaseUrl=http://anprdataprocessor:8080/api/
      - AnprDataProcessor__ClientId=3d6f0d98f00b204e9800998ecf8427e
      - AnprDataProcessor__ClientSecret=e99a18c428cb38d5f260853678922e03
    networks:
      - pol-assessment-network
    volumes:
      - ${HOTFOLDERS_PATH}:/app/HotFolders

networks:
  pol-assessment-network:
    external: true
