services:
  anprdataprocessor:
    image: anprdataprocessor
    container_name: anprdataprocessor-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Database__ConnectionString=Server=mariadb-container;Database=anprdata;User=user;Password=userpassword;
    ports:
      - "5100:8080"
      - "5101:8081"
    networks:
      - pol-assessment-network

networks:
  pol-assessment-network:
    external: true
